# fly.toml app configuration file generated for zeotap on 2024-10-26T23:06:36+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zeotap'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
