# docker-compose.yml

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Map Nginx on port 80 to localhost:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Express server port
    environment:
      - NODE_ENV=production
    restart: unless-stopped
